#!/bin/bash
set -e -E -u

DIST_DIR=dist

rm -rf $DIST_DIR
mkdir -p $DIST_DIR
cd $DIST_DIR
virtualenv -p /usr/bin/python2 venv
set +u
. venv/bin/activate
set -u

rm -rf tmp/
git clone https://github.com/netkraken/minion.git --depth 1 tmp

pip install cx_Freeze docopt countdb netkraken-minion
cxfreeze --include-path=$PWD --target-dir=netkraken-bin tmp/src/main/scripts/record-connections

tar zcvf netkraken-bin.tgz netkraken-bin/
