#!/bin/bash
set -e -E -u

BUILDHOST=${1:?no buildhost given?!}
MINION_DIR=minion
DIST_DIR=dist

(
    if [[ -d $MINION_DIR ]]; then
        cd $MINION_DIR
        git pull
        ./init-devenv
    else
        git clone https://github.com/netkraken/minion.git
        cd $MINION_DIR
        ./init-devenv
    fi
)

mkdir -p $DIST_DIR
cat minion/target/dist/*/dist/*.dev0.tar.gz | ssh $BUILDHOST '
    tar zxvf -
    cd netkraken*
    virtualenv venv
    . venv/bin/activate
    pip install cx_Freeze docopt
    echo $PWD > actual-pwd
    cxfreeze --include-path=$PWD --target-dir=netkraken-exe scripts/record-connections
    echo ____TAR_FOLLOWS_THIS_LINE____
    tar zcvf - netkraken-exe/
' | sed "1,/^____TAR_FOLLOWS_THIS_LINE____$/d" > $DIST_DIR/netkraken-exe.tgz
