#!/bin/bash
set -e -E -u

HOSTS=${1:?no hosts given?!}

export PDSH_SSH_ARGS="-q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

pdsh -f 32 -w $HOSTS ". /etc/profile; netkraken-bin/record-connections --rounds=10 --delay=30 < /dev/null > /dev/null 2>&1 &"
