#!/bin/bash
set -e -E -u

BIN_TGZ=dist/netkraken-bin.tgz

if [[ ! -e $BIN_TGZ ]]; then
    echo "cannot find $BIN_TGZ, aborting"
    exit 1
fi

for HOST in $*; do
    echo "distributing to $HOST"
    ssh -o LogLevel=error \
        -o ConnectTimeout=1 \
        -o CheckHostIP=no \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o BatchMode=yes \
        $HOST 'tar zxf -' < $BIN_TGZ || echo "problems while distributing to $HOST" >&2 &
    sleep 0.2
done
wait

echo "done."
